### ISSUE TITLE
Contact you!

### ISSUE THREAD

**Issue by janmarinka** [xan1242/NFSU-XtendedInput#1]
Hello Lovro,
hope you are doing well.
I had to open a issue because I have no other way of contacting you. I am extremely interasted in cooperating with you on NFS carbon server emulator. Please reach out to me if you are interasted.

Thanks!
Jan

**Comment by xan1242** [comment]
Hi,

(You should've opened an issue at the server repo, not here 😄)

You may contact me at Discord: Tenjoin#6673
