### ISSUE TITLE
Write a custom steering handler

### ISSUE THREAD

**Issue by xan1242** [xan1242/NFSU-XtendedInput#10]
This steering handler stinks:

![image](https://user-images.githubusercontent.com/8014093/193471280-d3949e84-6f96-45b3-b8f6-dd215084a19f.png)

Because:

- JOY_EVENT_STEER_ANALOG dies if JOY_EVENT_STEER is used
- Returning 0 doesn't return in a perfect 0 in steering value, instead it ends up with 0.0007 or something similar
- Analog steering resolution is limited to 8 bits, whereas XInput allows for 16 bits

Rewriting this will resolve these issues and allow for better steering control in games (not counting drag races)

**Comment by xan1242** [comment]
fixed in https://github.com/xan1242/NFSU-XtendedInput/commit/31f98570921225d22e2338852fd3dcf696422031

**Comment by xan1242** [comment]
@Nowena I've released it: https://github.com/xan1242/NFSU-XtendedInput/releases/tag/2.4

**Comment by Nowena** [comment]
It works, thank you. But the entry for dpad steering is null listing a '0'. I had to add 'XINPUT_GAMEPAD_DPAD_LEFT' and 'XINPUT_GAMEPAD_DPAD_RIGHT' for enabling both steerings at the same time. I don't know but since I already got familiar with the plugin, this might not be as obvious to other users.

I hope more people find your plugin. I saw several threads online for people asking about the same issue I had with shift up/down not mapping and your plugin solved it plus way more 🥳

**Comment by xan1242** [comment]
> It works, thank you. But the entry for dpad steering is null listing a '0'. I had to add 'XINPUT_GAMEPAD_DPAD_LEFT' and 'XINPUT_GAMEPAD_DPAD_RIGHT' for enabling both steerings at the same time. I don't know but since I already got familiar with the plugin, this might not be as obvious to other users.

It was purposefully done this way because the D-Pad was already bound to the in-game FE actions in UG2. I _could've_ left it for UG1 but I've also mapped some functions there too so it's kinda janky.

> I hope more people find your plugin. I saw several threads online for people asking about the same issue I had with shift up/down not mapping and your plugin solved it plus way more 🥳

Thanks! Currently the biggest limitation is the cumbersome INI editing which is what I'm trying to get around by implementing the ingame menus to cooperate with the ini reader.

It's a case of being a little too late with this kind of a plugin, that's why it's mostly unknown. I've already presented it to KuruHS (via MW) but he found the ini editing to be very annoying.

**Comment by Nowena** [comment]
> It was purposefully done this way because the D-Pad was already bound to the in-game FE actions in UG2. I _could've_ left it for UG1 but I've also mapped some functions there too so it's kinda janky.

I see but when I am in free roam mode, I cannot steer with the dpad; however, the map, sms, stats and entering events still work so there's no conflict that way. I tried a drift race and I was able to steer with both the dpad and left analog stick.

> Thanks! Currently the biggest limitation is the cumbersome INI editing which is what I'm trying to get around by implementing the ingame menus to cooperate with the ini reader. 
>
>It's a case of being a little too late with this kind of a plugin, that's why it's mostly unknown. I've already presented it to KuruHS (via MW) but he found the ini editing to be very annoying.

Well, pretty sure most plugins I've tried are managed with ini editing anyway. There is currently no other solution for the mapping issue affecting xinput devices aside from your plugin, I'm sure it'll catch on quick. But yea, having a more intuitive and graphic interface for remapping would surely give more attention to the plugin. Although, as it is, I am pretty pleased. Everything is as it should.

**Comment by Nowena** [comment]
Tested NFSU1 and your xtendedinput plugin works fine too with that game
