### ISSUE TITLE
Game Instant-Closes with this added

### ISSUE THREAD

**Issue by xamzy** [xan1242/NFSU-XtendedInput#13]
hello!

i'm having a little issue regarding the game instantly closing whilst XtendedInput is installed.

I've made a small video demonstrating what happens and my current attempts of solution and situation.

Any help is appreciated, or any pointers in the right direction. Thanks 

Video: https://youtu.be/Cw539VzRpT8

**Comment by xan1242** [comment]
From what I can see in the video, the executable is a little bit different size than usual.

I need you to check the following things:

- Are you running version 1.2
- Is your executable MD5 hash: 6445ADBF4E8D64BE51E96A69BBA168A4


If any of these don't match your settings, please install 1.2 and get the HOODLUM NoCD (attached below)

[SPEED2.zip](https://github.com/xan1242/NFSU-XtendedInput/files/9985511/SPEED2.zip)

**Comment by xamzy** [comment]
Hi! 

That’s most likely the issue, to be honest! I’ll give them a shot tomorrow after university - and let you know. 

I appreciate it :)

**Comment by xamzy** [comment]
Hello again!

Thanks for that, this solved all my problems :) muchly appreciated. 
One more small question - this could just be user error; but in the Drag Races I can't seem to shift up or down with any of the buttons on the controller? Is this something I have to map manually in the ini or am I just being dense? I seem to have to use Ctrl and Shift on the keyboard while controlling the car with a gamepad. 

Cheers.

**Comment by HarGabt** [comment]
@xamzy 
> with any of the buttons on the controller

Gear shifting is assigned to right analog stick movement by default. You're meant to move the stick up or down to shift.
Or it does not work as well on your version?

**Comment by xamzy** [comment]
Perfect!! Thank you so much :) I appreciate the help with it all. 
Case closed :)
