### ISSUE TITLE
Most of the buttons dont do anything

### ISSUE THREAD

**Issue by JormTheProto** [xan1242/NFSU-XtendedInput#15]
Installed this mod with Widescreen mod. NFS U1. When entering the game, I cant navigate the menu with buttons, with only a couple working like Q to Quit to Windows. When I'm in a race, none of the controls work.(Both on controller and on keyboard). I'm using Win 11 Pro 22H2, NSF U1 1.4 NoCD, DualShock 4 controller. I have disabled enchanced controls in the Widescreen Mod ini

**Comment by xan1242** [comment]
Use this executable and make sure ds4windows is configured to use XInput mode.

[Speed.zip](https://github.com/xan1242/NFSU-XtendedInput/files/10177228/Speed.zip)

**Comment by JormTheProto** [comment]
Is ds4windows a requirment for your mod? I wasn't using it when I tried playing NSFU with just widescreen mod(it worked fine apart from Square acting like Cross and Cross acting like Circle).

**Comment by HarGabt** [comment]
@R1st0n 
>Is ds4windows a requirment for your mod?

Well, if you happen to use non-XInput controller like DualShock/DualSense, you'll need some kind of an XInput wrapper like DS4Windows or via Steam Input

>apart from Square acting like Cross and Cross acting like Circle

This is an issue of DInput, as far as I know

**Comment by JormTheProto** [comment]
@xan1242 thanks. the exe swap fixed the issue for me. could you please tell me what is different in this exe?

**Comment by xan1242** [comment]
No idea what's different between yours and this one specifically, but they are the ones we actively use for modding. We tend to use fixed addresses to modify the memory and inject the code and this version specifically has the correct ones.

Also yes, you need ds4windows to emulate XInput. That's the name of the game when it comes to this plugin. It brings XInput to NFS, that's the entire point of it. 

I could try to re-introduce DInput but that's a whole other can of worms.
