### ISSUE TITLE
No input

### ISSUE THREAD

**Issue by ctnkyaumt** [xan1242/NFSU-XtendedInput#17]
I'm playing Underground 1 version 1.4.0. Trying to use this mod with widescreen fix mod. Commented out the options in the widescreen fix .ini file. Game opens up no problem but when it asks for input i cannot get past that screen to enter the main menu. Keyboard inputs do not seem to work either.

**Comment by HarGabt** [comment]
@ctnkyaumt 
Likely an executable incompatibility
[try this one](https://github.com/xan1242/NFSU-XtendedInput/files/10177228/Speed.zip)

**Comment by HarGabt** [comment]
Also, you didn't have to comment out the option in the Widescreen Fix - just make sure `ImproveGamepadSupport` is set to 0

**Comment by ctnkyaumt** [comment]
New .exe solved the problem. Thanks.

**Comment by HarGabt** [comment]
Close the issue, then.

**Comment by xan1242** [comment]
I get emails, no worries. 

Yeah, please close issues as resolved instead of just commenting if it works out, it's the button right next to the post button. As the author of the issue, you can do and should it.

I'll do it for now.
