### ISSUE TITLE
NFSU2 doesn't launch anymore when installed | NFSU2, Xbox Series S Controller

### ISSUE THREAD

**Issue by Kha1r0** [xan1242/NFSU-XtendedInput#19]
Hello there,
i put all the files in place, but when i start the game, the little nfsu2 picture appears, but the actual game doesnt open and the exe is ended. any troubleshooting steps worth trying? (Controller connected via Bluetooth/Cable/not at all doesnt make a difference.)
Thanks!

**Comment by xan1242** [comment]
Try with this executable: [SPEED2.zip](https://github.com/xan1242/NFSU-XtendedInput/files/10420620/SPEED2.zip)

**Comment by Kha1r0** [comment]
That did it. Thanks! (Maybe put that file in the documentation? :) )

**Comment by HarGabt** [comment]
>Maybe put that file in the documentation?

We can't do that: the game assets are copyrighted and doing so will put the project's existence under risk of being bombarded by EA.
A better solution would be noting game versions this mod is compatible with, as Xan noted below.

**Comment by xan1242** [comment]
https://github.com/xan1242/NFS_CustomFont#game-support

Despite this being an unrelated project, this table should show exact versions we use for modding.

My plan is to eventually add a pattern detector so it becomes more reliable with other versions (such as the one you may have).

I'll add this table somewhere in these projects as well.

**Comment by xan1242** [comment]
> > Maybe put that file in the documentation?
> 
> We can't do that: the game assets are copyrighted and doing so will put the project's existence under risk of being bombarded by EA.

The reason I put it here in this issue is exactly because I'm not really afraid of it happening (game is basically abandoned). If need be (like the GTA situation), I'll remove it if and when I get the notice to do so.

If I thought that I was at real risk, I would point him to get the no CD himself instead.

**Comment by Kha1r0** [comment]
Now my game is in endless loading screens 90% of the time... any ideas?

**Comment by xan1242** [comment]
You need to have the latest patch installed. Can you please send me your exe file that you used before?

**Comment by Kha1r0** [comment]
[SPEED2.zip](https://github.com/xan1242/NFSU-XtendedInput/files/10420650/SPEED2.zip)
i updated to 1.2 but it was a sketchy updater D:

**Comment by xan1242** [comment]
This exe you sent me is the same one I sent you. Are you 100% sure you sent me the correct exe?

**Comment by Kha1r0** [comment]
oops, i cant read.
[SPEED2 (2).zip](https://github.com/xan1242/NFSU-XtendedInput/files/10420661/SPEED2.2.zip)

**Comment by xan1242** [comment]
OK so from what I can tell this is the original DRM executable, but it seems to be 1.2 just like the HOODLUM one I sent you.

When does the loading get stuck? When entering a race/world or right when you enter the menu?

Also can you try putting this in your game to check if it also has infinite loading: [NFSU2_SkipFE.zip](https://github.com/xan1242/NFSU-XtendedInput/files/10420682/NFSU2_SkipFE.zip)

It should enter a race directly instead of the menu.

**Comment by Kha1r0** [comment]
with the same config, it sometimes gets stuck when starting the game, but when it gets through, it loads endlessly when starting a race (both career/quickrace). no problems occur when the controller isnt connected at all.

**Comment by Kha1r0** [comment]
the loading screens are just the normal loading screens but they dont terminate.

**Comment by Kha1r0** [comment]
the SkipFE works with full controller support.

**Comment by xan1242** [comment]
OK I need a couple more bits of information:

1. Can you test normal game (without SkipFE) while running as administrator
2. Which OS are you using? Win10 or Win11 or something else?

**Comment by xan1242** [comment]
Also:

3. Test with a new save file

**Comment by Kha1r0** [comment]
but its really only sometimes. ive removed the skipFE and used your EXE file. load into the carreer, start a race, return to freeroam, start the race again, return to freeroam again, now endless loading screen.

**Comment by Kha1r0** [comment]
1. i always run it as admin and with Compatibility mode for winXP SP2.
2. Win11 Pro 64bit, Ryzen 7 5800X, GTX 1060
3. will try

**Comment by Kha1r0** [comment]
3. new savegame, first race with rachels car. race loads perfectly, return to explore mode loading screen runs endlessly.

**Comment by xan1242** [comment]
I got it: it's likely this issue https://github.com/xan1242/NFS-XtendedInput/issues/44

I'm experiencing it right now as we speak, my controls don't work at all anymore and I'm also running Win11. Something changed in behavior between 10 and 11.

I'll push these fixes to this repo as well, please wait.

**Comment by xan1242** [comment]
The problems should go away if you try with `KeyboardReadingMode = 2` in the ini file BTW

**Comment by Kha1r0** [comment]
That works! forgot to try and change it after the new exe. Thanks, that makes my install work perfectly!

**Comment by xan1242** [comment]
OK! I still have to _actually_ fix the problem in the code... It'll be done ASAP.

**Comment by Kha1r0** [comment]
next thing ill try is making it work in my arm macOS windows 11 parallels vm, but im not gonna bother you with that xD

**Comment by xan1242** [comment]
[NFSU_XtendedInput.zip](https://github.com/xan1242/NFSU-XtendedInput/files/10420763/NFSU_XtendedInput.zip)

Can you please revert KeyboardReadingMode to 0 in the ini and try this build? It should be OK now.

**Comment by Kha1r0** [comment]
nope, that didnt do it. :(

**Comment by Kha1r0** [comment]
(loading into freeroam first try)

**Comment by Kha1r0** [comment]
tried it again, load into freeroam, start race, return, start race, return, start race loads infinitely.

**Comment by xan1242** [comment]
Interesting that raw input mode fixes the problem for you... I don't quite understand why would that be the case other than the aforementioned issue with Win11...

Does the same happen in NFSMW and newer with [NFS_XtendedInput](https://github.com/xan1242/NFS-XtendedInput)? If it happens there as well then there might be something with the polling code in Win32 that's messing up stuff.

One more bit of info; which OS build are you running? I'm personally on 22H2 22621.1105

**Comment by Kha1r0** [comment]
because i talked shit. reverted back, and the issue was back. it could be some weird thing but i think i just didnt test it enough. so problem persists

**Comment by HarGabt** [comment]
@Kha1r0 Do you happen to have Extra Options? I had similar issue when using it, or it has nothing to do with it?

**Comment by Kha1r0** [comment]
i dont have nfsmw installed atm,
im on 11 pro 22H2 22621.1105.

**Comment by xan1242** [comment]
Wait so just so we're in the clear - you're using `KeyboardReadingMode = 2` and still have issues?

**Comment by Kha1r0** [comment]
@HarGabt i didnt change anything besides KeyboardReadingMode = 2

**Comment by Kha1r0** [comment]
@xan1242 yes, sorry for the confusion, i just didnt test it enough

**Comment by Kha1r0** [comment]
but its always at the same time with KeyboardReadingMode = 2, always the third time

**Comment by xan1242** [comment]
In that case, the only thing I can blame is your copy of the game which is being weird.

1. What else do you have in the scripts folder and in the game root directory?
2. Test thoroughly without my plugin and see if the issue still happens.
3. Get the latest WS fix as well
4. Disable Unlock106AndCorsa in ExOpts if you have it installed
5. If nothing else works, try obtaining the US version of the game (archive.org or myabandonware have them hosted) and patch it to 1.2 or find one pre-patched.

It doesn't really make sense to me why it would cause infinite loading otherwise. NFSU2 build especially - it doesn't even load any textures like NFSU build does.

**Comment by xan1242** [comment]
Also one more detail - disable WinXP SP2 compatibility mode. It is not needed and it also might be causing issues.

**Comment by xan1242** [comment]
And if the game is rendering at higher than 120FPS, enable VSync as well

**Comment by Kha1r0** [comment]
1. only the thirteenag widescreenfix https://thirteenag.github.io/wfp
2. will try :)
3. already have it
4. dont have them installed
5. could do that, but ill rather just use the keyboard

will disable and report back
will turn on. :) 144hz

**Comment by xan1242** [comment]
Are you absolutely sure you have no other DLL file in the game root than dinput8.dll and server.dll? This is important and a minute detail many forget about.

**Comment by Kha1r0** [comment]
winXP compatibility mode disable, vsync enable didnt fix it.
![image](https://user-images.githubusercontent.com/115714947/212557867-3cdc2255-adfa-4f7d-b60a-3fee8c187c4b.png)

**Comment by Spitzy24** [comment]
Hi all,

I'm experiencing the same problem as @Kha1r0, downloaded the mod and dragged the scripts folder and dinput8.dll file into the game's root directory, try to launch the game and have it crash immediately. I've tried getting it to work with the Widescreen Mod (thought there was some possible conflict, but same issue occurs with Input mod by itself too), no dice. I'm using a Asia-Pacific 2-CD version with UK update 1.2, and a Xbox One wired controller. Is there anything else I can do? I just wanna play the game without being stuck in an infinite loading screen by trying to change the controller mapping in-game :').

**Comment by Kha1r0** [comment]
My solution was switching from my CD version to the oldgamesdownload version. Fixed my many problems instantly and german->english didn't bother me half as much as i thought it would.

**Comment by Spitzy24** [comment]
> My solution was switching from my CD version to the oldgamesdownload version. Fixed my many problems instantly and german->english didn't bother me half as much as i thought it would.

The version you found was German only or English only?

**Comment by Kha1r0** [comment]
That version was english only.

**Comment by Spitzy24** [comment]
Ah, I see. So, looking on the oldgamesdownload/myabandonware sites, the install process looks... complicated. How easy did you find it to install?

**Comment by Kha1r0** [comment]
it was literally downloading and running the exe. Idk what you are seeing.

**Comment by nicktorress** [comment]
its happen to me too. i download the iso (disc 1) again and i ran

**Comment by bradley-varol** [comment]
I have this issue with this mod. Using oldgamesdownload + latest version of underground.net 🤔
