### ISSUE TITLE
Additional clearence & letting you know :)

### ISSUE THREAD

**Issue by janmarinka** [xan1242/NFSU-XtendedInput#2]
Hi Lovro,
hope you are doing well.
I have added you on discord, I sent a friend request. My discord username is Jаn#3370.

As well I wanted to clear out that I cannot create a thread in the Carbon itself, because its a forked off repository and that does not allow issues. 

Thank you for understanding,
Jan!

**Comment by xan1242** [comment]
Oh... right, sorry. I'll detach the repo sometime soon then.
