### ISSUE TITLE
No controller input in the game but menu works fine.

### ISSUE THREAD

**Issue by Echo-Wxlf** [xan1242/NFSU-XtendedInput#20]
Default keyboard controls also work fine (primary input only), It's like the game forgets I have a controller plugged in. I'm using a DS4 with DS4windows in xinput mode. I have the extra options and widescreen fix mods installed too. Any ideas how to fix this?

**Comment by Echo-Wxlf** [comment]
Underground 2 btw

**Comment by xan1242** [comment]
To clarify; can your gamepad control menus or not?

**Comment by Echo-Wxlf** [comment]
Yes.

**Comment by Echo-Wxlf** [comment]
It's probably just user error, Heh. 
I did spend a decent amount of time looking over stuff though.

**Comment by xan1242** [comment]
I don't have a DS4 at hand currently, so I'd need you to check one thing for me if you can.

Try enabling "Hide DS4 Controller" in DS4Windows' settings.

I'm not sure if DInput is interfering somehow

**Comment by Echo-Wxlf** [comment]
Aight will do. Hold on

**Comment by Echo-Wxlf** [comment]
No change.

**Comment by Echo-Wxlf** [comment]
DS4Windows' Xinput checker shows that the controller is using channel / virtual port 2, but I wasn't able to find an option to change it back to one, could that be the issue?
Oh also all input is registered in the checker perfectly fine.

**Comment by xan1242** [comment]
Yes, that seems to be the problem. The menus can be controlled by the second player (like on the console versions).

Try enabling debug cameras using this plugin: [DebugCams.zip](https://github.com/xan1242/NFSU-XtendedInput/files/10475609/DebugCams.zip)

Press backspace on the keyboard (or select on the second controller) while ingame to trigger it and see if you can control it with your gamepad. If that's the case, then you have to put it to port 1.

Usually restarting the vigembus service fixes it, but I'm not certain how to change it back now that I don't have a DS4.

**Comment by xan1242** [comment]
I've just tested it with 2 controllers and I can confirm the same behavior as yours. Menus can be controlled by the second player just fine, but not when you go ingame.

**Comment by Echo-Wxlf** [comment]
Ah I see. Alrighty.. well if I don't manage to fix it, at least I have some cool debug features! xd.

**Comment by Echo-Wxlf** [comment]
Yeah! I got it to work! Screw you... old tech!

**Comment by Echo-Wxlf** [comment]
Thanks a lot, though. For just a silly passion project you way overdid it, replying instantly and providing as much help as possible. I hope you make it as a developer, if you haven't already.

**Comment by xan1242** [comment]
> Thanks a lot, though. For just a silly passion project you way overdid it, replying instantly and providing as much help as possible. I hope you make it as a developer, if you haven't already.

@Echo-Wxlf 

Sorry for replying late to this, but thank you for the kind words!

I'm not a professional developer by any means. I hope it does happen in some capacity, though!
