### ISSUE TITLE
[Bug?] xan's fork of ReShade overrides the ability to toggle debug cameras

### ISSUE THREAD

**Issue by HarGabt** [xan1242/NFSU-XtendedInput#3]
I wouldn't call this a bug, but rather a conflict. 
So, if you have xan's fork of ReShade installed along with the XtendedInput, make sure to check `Debug cameras enabled` in NFS Tweaks.

**Comment by xan1242** [comment]
I'm only seeing this now...

The ability to trigger the debug cameras (the enable flag) is not something this plugin affects whatsoever.

My ReShade fork also has nothing to do with this either, it only visualizes the enable flag and allows you to affect it.

The main way to trigger it is through the debug menu, which is accessed through the ingame Options menu.

In any case, this is irrelevant to this plugin, closing.
