### ISSUE TITLE
How to use right analog stick for camera?

### ISSUE THREAD

**Issue by ks202005** [xan1242/NFSU-XtendedInput#4]
The [PCGamingWiki article on Need for Speed: Underground 2](https://www.pcgamingwiki.com/wiki/Need_for_Speed:_Underground_2) mentions that NFSU-XtendedInput "Reimplements console-like controls with being able to move the camera with the right stick." For me, it doesn't seem to work out of the box with my Logitech F310 using its XInput mode, while everything else seems to work fine. I had a look through the NFSU_XtendedInput.ini and I can't determine what the correct JOY_EVENT for camera controls is. What are they?

Also, as a relatively unimportant side note: In EventReference.txt, I got confused because I was trying to bind JOY_EVENT_CAMERA_LOOKBACK to the Left Bumper, but instead of XINPUT_GAMEPAD_LB (in the same manner as left trigger and left stick), it's XINPUT_GAMEPAD_LEFT_SHOULDER. Maybe it's just me getting confused with the 3 different ways of referring to the same buttons (bumper/L1 and R1/shoulder) but it might be worth mentioning in EventReference.txt.

**Comment by xan1242** [comment]
> The [PCGamingWiki article on Need for Speed: Underground 2](https://www.pcgamingwiki.com/wiki/Need_for_Speed:_Underground_2) mentions that NFSU-XtendedInput "Reimplements console-like controls with being able to move the camera with the right stick." For me, it doesn't seem to work out of the box with my Logitech F310 using its XInput mode, while everything else seems to work fine. I had a look through the NFSU_XtendedInput.ini and I can't determine what the correct JOY_EVENT for camera controls is. What are they?

Whoever wrote that failed to mention that's related only to the Debug World Camera. It's the JOY_EVENT_DEBUG_CAMERA events which do that.

Or, alternatively, if we're talking about the menus (frontend), it's the JOY_EVENT_CARSEL_ORBIT events.

Just look at any event which uses XINPUT_GAMEPAD_RS_X or XINPUT_GAMEPAD_RS_Y.

I've tested with both a 360 and Xbox One controller, both worked fine so I'm not sure why it wouldn't work.

> Also, as a relatively unimportant side note: In EventReference.txt, I got confused because I was trying to bind JOY_EVENT_CAMERA_LOOKBACK to the Left Bumper, but instead of XINPUT_GAMEPAD_LB (in the same manner as left trigger and left stick), it's XINPUT_GAMEPAD_LEFT_SHOULDER. Maybe it's just me getting confused with the 3 different ways of referring to the same buttons (bumper/L1 and R1/shoulder) but it might be worth mentioning in EventReference.txt.

Maybe, but right now there *is* no mention of XINPUT_GAMEPAD_LB anywhere. I just took the names directly from the API and used them as a basis. It could be better, I agree, but this I will (hopefully) negate by simply making the configuration work in the game directly (so I'm not worrying about this disambiguation too much).

**Comment by ks202005** [comment]
>Whoever wrote that failed to mention that's related only to the Debug World Camera. It's the JOY_EVENT_DEBUG_CAMERA events which do that.

Ah, I see; so there's no way to move the camera around in the regular game? I'll correct the article if that's the case.

>right now there is no mention of XINPUT_GAMEPAD_LB anywhere. I just took the names directly from the API and used them as a basis

No worries! I didn't mean to imply that *you* were behind this decision, since while searching elsewhere for what the correct strings for the bumpers were I realized these were regular XInput calls, and I don't blame you for not adding some abstraction layer. By "it might be worth mentioning in EventReference.txt", I meant maybe a note saying something like "The Bumpers are XINPUT_GAMEPAD_LEFT_SHOULDER and XINPUT_GAMEPAD_RIGHT_SHOULDER and not .....LB/RB like one might expect".

**Comment by xan1242** [comment]
> Ah, I see; so there's no way to move the camera around in the regular game? I'll correct the article if that's the case.

Yes. This addon doesn't introduce any new features per se, it's all the same features already in the console versions as far as gamepad controls are concerned (besides rumble, which I'll be working on).

So the only places where the right stick controls the camera are the debug cameras and menus, just like in the regular games.

While making this feature isn't too far fetched, it isn't in the scope of this project. So if you ever see this from me, it'll be a separate mod (and a repo for it).

> No worries! I didn't mean to imply that _you_ were behind this decision, since while searching elsewhere for what the correct strings for the bumpers were I realized these were regular XInput calls, and I don't blame you for not adding some abstraction layer. By "it might be worth mentioning in EventReference.txt", I meant maybe a note saying something like "The Bumpers are XINPUT_GAMEPAD_LEFT_SHOULDER and XINPUT_GAMEPAD_RIGHT_SHOULDER and not .....LB/RB like one might expect".

I could one-up this by adding it in as an option so people can't mess up. It's really not a big problem, so I'll do just that (in both this one and the one for newer games). I'll add it in when I get around to it.

**Comment by ks202005** [comment]
>Yes. This addon doesn't introduce any new features per se, it's all the same features already in the console versions as far as gamepad controls are concerned (besides rumble, which I'll be working on).

I've corrected the article. Rumble would be a great addition!

>While making this feature isn't too far fetched, it isn't in the scope of this project. So if you ever see this from me, it'll be a separate mod (and a repo for it).

It would be a very cool feature, but I guess it's not totally necessary. I actually had assumed the console versions of both Underground games had this, so it's interesting that they don't.

>I could one-up this by adding it in as an option so people can't mess up. It's really not a big problem, so I'll do just that (in both this one and the one for newer games). I'll add it in when I get around to it.

Nice! Thanks for putting in such effort into making this mod. 

I do have one further question I want to ask so I can improve the PCGamingWiki article: does the file dinput8.dll load all .asi files found in the \Scripts\ Directory? I had installed ThirteenAG's Widescreen Fix mod prior to installing NFSU-XtendedInput and the ThirteenAG mod still works. I want to clarify the PCGamingWiki article because it lists 3 separate mods that all have some overlap in apparent functionality (ThirteenAG's mod also adds XInput support; not sure if it's related in anyway to your code or having both mods installed causes conflicts) and it's quite confusing as to whether or not you can have all of them installed at once.

**Comment by xan1242** [comment]
Yes, dinput8.dll here is basically the same thing. It's ThirteenAG's Ultimate ASI Loader, so overwriting one with the other shouldn't affect anything (in the case you have both installed and enabled).

As for the WS Fix and the improved controller support - it's not related to this project. It shouldn't affect anything except icon swapping in menus.

I've developed these with the WS Fix and Extra Options in mind, so even if some features overlap, it'll still work.

**Comment by HarGabt** [comment]
>Whoever wrote that failed to mention that's related only to the Debug World Camera. It's the JOY_EVENT_DEBUG_CAMERA events which do that. Or, alternatively, if we're talking about the menus (frontend), it's the JOY_EVENT_CARSEL_ORBIT events.

I wrote that, it was my oversight during filling the pages in PCGamingWiki with NFS(U)-XtendedInput. Yes, i happened to have forgotten to mention in UG2 page that it does apply only to Debug World Camera and Garage carousel (FrontEnd).
My bad.

>I've corrected the article

I don't think it was necessary to get rid of the whole line of that claim, best option was to add the missing mention of aforementioned actions with debug camera and garage camera. 
Once again, my bad of not adding it.

**Comment by xan1242** [comment]
added XINPUT_GAMEPAD_LB and XINPUT_GAMEPAD_RB in https://github.com/xan1242/NFSU-XtendedInput/commit/757b4a31b14e624ad2634529ef84f999f4e9c549

Closing.
