### ISSUE TITLE
Widescreen Patch + XtendedInput not working together

### ISSUE THREAD

**Issue by AlphaNERD-** [xan1242/NFSU-XtendedInput#5]
Hello,

so i recently found the Xtended Input mod and wanted to try it out on my PC. I have previously installed ThirteenAg's Widescreen patch. The input is working fine thanks to the patch but the fixed button prompts from Xtended Input sounded nice.

Anyway i installed the Xtended Input mode and i can't get the mods to work together. The game cannot start up if i want to use both.

**Comment by xan1242** [comment]
Which version of the game are you running?

Mods are usually made for 1.4.0 only.

Secondly, you may want to disable WS fix's input fix. This plugin handles everything.

I have developed this with WS fix and it works fine for me.

**Comment by AlphaNERD-** [comment]
I forgot to specify: I am playing NFS Underground 2. I haven't installed a patch for it yet. Do i need patch 1.2 or 2.0?

**Comment by AlphaNERD-** [comment]
I just finished trying to get the mod working with 1.1 and 1.2. No success. Something i noticed is that you didn't add a resource file for the global directory like you did with the Underground 1 version of XtendedInput. Is that supposed to be like this?

**Comment by xan1242** [comment]
Yes, I hadn't implemented the swapping in Underground 2 yet (help menus don't show the textures yet for various other reasons). This is something I plan on adding back as well.

If it's Underground 2 you're playing, then it's the latest version with the NoCD patch that you need to use. Can't remember off the top of my head which one it is (Extra Options uses it too and even contains a check for it). I'll get back to you once I get to a computer.

**Comment by xan1242** [comment]
Alright, so the version I used is 1.2 by HOODLUM.

md5sum is `6445adbf4e8d64be51e96a69bba168a4`.

Use that one as it is the standard one we're all using during modding.

**Comment by AlphaNERD-** [comment]
Sorry for the late answer. The HOODLUM patch works indeed. New problem: Two of my devices do not have an optical drive. The HOODLUM No-CD patch requires the existence of an optical drive. I could hook up a USB drive to the 2 devices but then i might as well insert the legitimate copy i got which defeats the purpose of the No-CD patch 😆 

All i wanna say is: Can you please make the mod work with different No-CD patches like from FFF? If not that's okay. I can make an empty ISO file and mount it in Windows to simulate a drive.

**Comment by AlphaNERD-** [comment]
[EmptyISO.zip](https://github.com/xan1242/NFSU-XtendedInput/files/8879162/EmptyISO.zip)

Okay, i just made a bare ISO. I named it EmptyISO although that's a misnomer because there's a little Readme.txt inside. Should anyone ask in the future about an "Insert Disc 2" message, you can hand them the ISO file.

**Comment by xan1242** [comment]
> All i wanna say is: Can you please make the mod work with different No-CD patches like from FFF? If not that's okay. I can make an empty ISO file and mount it in Windows to simulate a drive.

Not really, at least not at the moment.

The reason I (and other modders) avoid using the other versions (including the original one with DRM) is simply because they're not friendly to disassemblers and are prone to crashing if any code is modified (because of the DRM).

It could potentially be done with pattern detection (much like the WS fix) but it isn't a priority since lots of people just stick to this one version anyways.

As for the NoCD version requiring a CD drive existing, that is something that can be fixed with a separate patch. I can look into it and fix it.

> Okay, i just made a bare ISO. I named it EmptyISO although that's a misnomer because there's a little Readme.txt inside. Should anyone ask in the future about an "Insert Disc 2" message, you can hand them the ISO file.

I don't think this would be necessary. Patching the game outright is an easier way, which I'll do instead.

**Comment by AlphaNERD-** [comment]
Hey, uuuh, little question: Have you managed to patch out the "Insert Disc 2" message meanwhile?

**Comment by 12stiggy12** [comment]
Hello, I am also having an issue with the widescreen patch and XtendedInput. The game will launch around 100x100 pixels away from the corner. https://i.imgur.com/fmDHybU.png 

I'm using a temporary workaround at the moment, but was wondering if you could explain on how you managed to fix it. I have checked that i'm using the correct hoodlum no cd crack. 

The workaround im using is to change the scaling options in my nvidia control panel settings, or anything that causes a display refresh will cause the issue to go away.

**Comment by xan1242** [comment]
@12stiggy12 I'm making a new issue. Your bug is unrelated to this report. Go here: https://github.com/xan1242/NFSU-XtendedInput/issues/7
