### ISSUE TITLE
(Underground) Incorrect work of Xtended input and crash when pressing back/view button

### ISSUE THREAD

**Issue by RostovShev03** [xan1242/NFSU-XtendedInput#6]
I set ImprooveGamepadSupport on 0 in WidescreenFix.ini, installed Xtended input on this game, ran this game. On title screen it says "Press Enter" instead "Press A button". Button icons doesn't change at all, whatever I used: Keyboard or gamepad. Anyway all buttons on gamepad works correctly, but when I press back/view button, the game crashes. I don't know what wrong is. My no-CD is 1.4 crack DRUNK

**Comment by xan1242** [comment]
Are you _sure_ you used the correct build? The ASI should have a md5sum of `20FF6D8EE44399BCBD71046F0D57DBA4`

Make sure you're using the ASI from Release-UG-Pack.zip and not the UG2 variant.

**Comment by RostovShev03** [comment]
Now it works good! Looks like I used Europen version of NFS Underground insted of US one. Thanks!
