### ISSUE TITLE
Game launching 100 pixels from corner with WS fix

### ISSUE THREAD

**Issue by xan1242** [xan1242/NFSU-XtendedInput#7]
> Hello, I am also having an issue with the widescreen patch and XtendedInput. The game will launch around 100x100 pixels away from the corner. https://i.imgur.com/fmDHybU.png
> 
> I'm using a temporary workaround at the moment, but was wondering if you could explain on how you managed to fix it. I have checked that i'm using the correct hoodlum no cd crack.
> 
> The workaround im using is to change the scaling options in my nvidia control panel settings, or anything that causes a display refresh will cause the issue to go away.
> 
> _Originally posted by @12stiggy12 in [#5 (comment)](https://github.com/xan1242/NFSU-XtendedInput/issues/5#issuecomment-1251507485)_

_Originally posted by @12stiggy12 in https://github.com/xan1242/NFSU-XtendedInput/issues/5#issuecomment-1251507485_

**Comment by xan1242** [comment]
@12stiggy12 Can you confirm this happening with XtendedInput and WS fix being *together*? I don't think this is something caused by the input plugin, but a bug by the D3D overlay you're using (RTSS)

**Comment by 12stiggy12** [comment]
The overlay was not causing the issue. Im using extra options for the borderless mode. Should i use BorderlessGaming instead?
Obviously running in fullscreen fixes the issue.

**Comment by xan1242** [comment]
> Im using extra options for the borderless mode.

There's your problem. ExOpts didn't implement this properly whatsoever. Don't use that.

You can use my windowed mode fix here: https://github.com/xan1242/NFSU_WindowedMode

I'm planning to port this code to the WS fix for native support soon so expect it there.

**Comment by 12stiggy12** [comment]
Thanks for the quick responses, will that work with underground 2? I should have mentioned this earlier.

**Comment by xan1242** [comment]
Unfortunately it won't work, however, I'll port it to WS fix for UG2 eventually so it'll be available for UG2 that way soon.

**Comment by 12stiggy12** [comment]
Any ideas on what to use in the meantime? Should i just continue to use my workaround?

**Comment by xan1242** [comment]
You can use your workaround or things like DXWnd to try to relocate the window. Anything is valid. 100x100 location is hardcoded in the executable for some reason so it'll always appear there.

Another idea is that you can manually set it to 0 by writing 0 to 0x1D2607 in the SPEED2.EXE (0x005D2607 in memory) to negate that window movement. You can use any hex editor to do this, such as HxD. It's a hack but it'll work out.

**Comment by 12stiggy12** [comment]
Changing that address in HxD (0x1D2607) causes the game to be cut off around the edges.

**Comment by xan1242** [comment]
[nfsu2_windowedmode.zip](https://github.com/xan1242/NFSU-XtendedInput/files/9602359/nfsu2_windowedmode.zip)

Use this then, I've just quickly ported the WindowedMode for UG1 I made to UG2. It should work exactly the same.

**Comment by 12stiggy12** [comment]
Thanks alot. That works perfectly.

**Comment by xan1242** [comment]
Closing issue as solved. (Even though it was unrelated to XtendedInput)

**Comment by Nowena** [comment]
Don't know where else to comment about this since you archived the repository for NFSU windowed mode but yea I read that note and I have the WS fix version from 06 Jul 2022, that's the latest one, no? Downloaded from here https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/nfsu

Must not be the one you are talking about since it's not working and I don't see an option for windowed mode in the ini file. That's why I thought of trying the plugin you archived but it isn't working either.

**Comment by xan1242** [comment]
Go to website: http://thirteenag.github.io/wfp#nfs

And in the drop down menu you can get the dev build.

It's not gonna fix your issue immediately as I need to implement fixes to this plugin first. It'll be done later.

**Comment by Nowena** [comment]
Aight, thank you. But I like windowed mode cuz sometimes I pause the game for a bit to click on stuff outside of it, the dev build may fix the resizing issue but then the pointer cannot click outside anything from the game so there's no point in having windowed mode that way if I can't do that. I'll just wait till the pointer thing is fixed and will play the game in full screen in the meantime.

**Comment by xan1242** [comment]
But the entire point is that I integrated windowed mode to WS fix! Go to the ini file to enable it.

Or did you mean the relocation? If you want it, I can add it in.

Edit: oh, sorry, yeah, the mouse thingy will get added in, no worries. Win32 cursor is coming soon: https://github.com/xan1242/NFSU-XtendedInput/issues/12

**Comment by Nowena** [comment]
Yes, I do understand you integrated windowed mode into WS fix but like you realised, I was saying I need to wait until the mouse cursor/pointer issue is solved. Just let me know when it's ready, thank you.
