### ISSUE TITLE
Conflict with extra options' Windowed mode

### ISSUE THREAD

**Issue by Nowena** [xan1242/NFSU-XtendedInput#8]
Hi.

I came across this plugin whilst trying to find a way to map the shift up/down inputs with left and right triggers of a joystick and I have extra options for Underground 2 installed with the bordered windowed mode enabled. Your plugin has a conflic with it and the game runs in a semi-full-screen instead but it's like kinda minimised and you can neither enter full-screen nor resize the window.

**Comment by HarGabt** [comment]
@Nowena 
Extra Options may be the culprit in this.
Check this issue: https://github.com/xan1242/NFSU-XtendedInput/issues/7

**Comment by xan1242** [comment]
Yes, @HarGabt is right.

As described in the issue, it'll get combined with WS fix when I get the time to do it. You may actually use the ASI from the issue there.

(I'm giving myself an ETA of this weekend, but don't take this as 100%)

**Comment by Nowena** [comment]
Ok thanks, this is solved. But I still need help with the throttle and brake issue.

**Comment by xan1242** [comment]
No need to close the issue then if there's a problem. I'm reopening this one.

**Comment by xan1242** [comment]
So - to map shift up/down to LT/RT, just set the following:

```
JOY_EVENT_SHIFTUP = XINPUT_GAMEPAD_RT
JOY_EVENT_SHIFTDOWN = XINPUT_GAMEPAD_LT
```

To set throttle/brakes (for analog input):

```
JOY_EVENT_THROTTLE_ANALOG = XINPUT_GAMEPAD_RS_UP
JOY_EVENT_BRAKE_ANALOG = XINPUT_GAMEPAD_RS_DOWN
```

Or if you want face buttons, like on the PS2 controller:

```
JOY_EVENT_THROTTLE = XINPUT_GAMEPAD_A
JOY_EVENT_BRAKE = XINPUT_GAMEPAD_X
```

I am also planning to write a configurator tool in the meantime (until the ingame menus are sorted) so you'd have a GUI to configure stuff (instead of a text file). 

Let me know if this works out for you. If it does, then you may close the issue again.

**Comment by Nowena** [comment]
Well, I closed it cuz this issue was originally about windowed mode and that got solved, I had opened a different issue for the mapping.

But yea I had already set shift up/down but I don't know if those mapped correctly cuz I can't shift without being able to use the throttle.

And I'm trying to set face buttons A (Cross on PS2) and X (Square on PS2) for throttle and brake but I already thought of using an entry without the _ANALOG line like you suggested, still doesn't work :(

**Comment by xan1242** [comment]
Oh shoot lol, sorry, didn't even LOOK and it went under my radar, sorry. OK, moving over there then...

Continuing in: https://github.com/xan1242/NFSU-XtendedInput/issues/9
