### ISSUE TITLE
Unable to remap throttle and brake input correctly

### ISSUE THREAD

**Issue by Nowena** [xan1242/NFSU-XtendedInput#9]
I mentioned my initial issue was I was trying to correctly map the shift up/down inputs for Underground 2 with right and left triggers of a joystick and your plugin looked like it was gonna be the solution but I ended up encountering another issue as frustrating as the initial one. The default mappings for throttle and brake work, it's when I try to remap them to xinput 'A' and 'X' that they don't work.

All the other remapping worked, just not these two.

**Comment by Nowena** [comment]
Maybe it has to do with the fact the entries for throttle and brake are laballed as 'ANALOG'?

**Comment by xan1242** [comment]
>Well, I closed it cuz this issue was originally about windowed mode and that got solved, I had opened a different issue for the mapping.

>But yea I had already set shift up/down but I don't know if those mapped correctly cuz I can't shift without being able to use the throttle.

>And I'm trying to set face buttons A (Cross on PS2) and X (Square on PS2) for throttle and brake but I already thought of using an entry without the _ANALOG line like you suggested, still doesn't work :(

_Originally posted by @Nowena in https://github.com/xan1242/NFSU-XtendedInput/issues/8#issuecomment-1263817053_

OK so let's continue here.

So as far as I understood - mapping digital buttons didn't work for you... I'll check it out.

**Comment by Nowena** [comment]
Yes, that's it. Throttle and brake worked when they were mapped to the default right and left triggers, it's when I try to remap them with A and X that it doesn't work.

**Comment by xan1242** [comment]
I had this same issue on keyboard input and I seemingly forgot to apply it to gamepad inputs...

I fixed it with this commit now: https://github.com/xan1242/NFSU-XtendedInput/commit/3f7cad1090ef2c84de86e212a10e1432efaa9ecc

I'll create new builds now with which you can test...

**Comment by xan1242** [comment]
[Release-UG-Pack.zip](https://github.com/xan1242/NFSU-XtendedInput/files/9686594/Release-UG-Pack.zip)
[Release-UG2-Pack.zip](https://github.com/xan1242/NFSU-XtendedInput/files/9686596/Release-UG2-Pack.zip)

Please test with the game which applies to your case. If it's all well, I'm releasing these as the next version.

**Comment by Nowena** [comment]
All working fine with U2! Thank you for the quick response and fix :)

**Comment by xan1242** [comment]
Alright, no problem!

Fixed in https://github.com/xan1242/NFSU-XtendedInput/commit/3f7cad1090ef2c84de86e212a10e1432efaa9ecc

**Comment by Nowena** [comment]
So I may close the issue?

**Comment by Nowena** [comment]
Question: is it possible to map steering with both the D-pad and the left stick X axis? I feel I drift better with the D-pad and just want to switch the steering control for that occasion then return it to the left stick when I'm doing regular races, as it was possible when playing the PS2 version.

**Comment by xan1242** [comment]
I've written there in the INI

```
JOY_EVENT_STEER = XINPUT_GAMEPAD_LS_X
// commented out analog because it causes issues, when regular steer is activated, analog steering dies
//JOY_EVENT_STEER_ANALOG = XINPUT_GAMEPAD_LS_X
```

For _some_ reason it's one or the other at the moment... I could work around this by making this distinction within the plugin instead of relying on the game, which is what I'll probably do.

**Comment by Nowena** [comment]
Oh yea, I read that but I didn't quite understand what it meant, I was confused cuz I thought 'analog' here referred to 'analog stick' being the default option and saw it was disabled.

I'm still a bit confused about which are analog and digital buttons since the triggers are apparently analog and A and X are digital.

So in this case here, 'analog' refers to the D-pad and the left stick would be digital? 🤔

**Comment by xan1242** [comment]
What it actually refers to is the joy event name. Black Box made 2 separate joy events for steering, for obvious reasons, but the values it reads are the exact same in UG1.

This is probably a leftover from HP2 code I assume, that's why it's named the way it is and works both ways.

**Comment by Nowena** [comment]
ah ok, hope you can enable both steerings when you have time.

**Comment by Nowena** [comment]
Any possibility to have both steerings enabled soon? I'm finding it impossible to drift with the analog stick, especially downhill drifting.

**Comment by xan1242** [comment]
I'm in the process of writing a custom steering handler which will not only resolve this issue, but increase the resolution of the analog axis.

Refer to https://github.com/xan1242/NFSU-XtendedInput/issues/10

**Comment by Nowena** [comment]
Sounds great, patiently awaiting until it's ready. Thank you.
